# Generated by Django 4.1.7 on 2023-04-08 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_alter_user_options_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
