# Generated by Django 4.1.7 on 2023-04-13 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('graduate_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=255, null=True)),
                ('class_code', models.CharField(max_length=255, null=True)),
                ('class_code_name', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('established_at', models.DateTimeField(null=True)),
                ('sggu_name', models.CharField(max_length=255, null=True)),
                ('emdong_name', models.CharField(max_length=255, null=True)),
                ('post_no', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('sido_name', models.CharField(max_length=255, null=True)),
                ('sggu_no', models.IntegerField(null=True)),
                ('sido_no', models.IntegerField(null=True)),
                ('general_doctor_count', models.IntegerField(null=True)),
                ('intern_count', models.IntegerField(null=True)),
                ('resident_count', models.IntegerField(null=True)),
                ('fellow_doctor_count', models.IntegerField(null=True)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.doctor')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hospitals',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='graduate_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.school'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.major'),
        ),
    ]
