# Generated by Django 4.1.7 on 2023-04-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='graduate_year',
            field=models.DateField(null=True),
        ),
    ]
