# Generated by Django 4.1.7 on 2023-05-14 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_remove_saleshistory_history_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleshistory',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosp', to='hospital.hospital'),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='status',
            field=models.CharField(choices=[(1, 'ACT'), (2, 'BEST_CASE'), (3, 'PIPELINE'), (4, 'OPP'), (5, 'FUNNEL')], default=1, max_length=10),
        ),
    ]
