# Generated by Django 4.1.7 on 2023-05-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_saleshistory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_own_product', models.BooleanField(default=False)),
                ('hospital', models.ManyToManyField(null=True, related_name='product', to='hospital.hospital')),
            ],
        ),
    ]
